### ISSUE TITLE
disable recursive watches

### ISSUE THREAD

**Issue by rtennill** [avar/app-inotify-hookable#4]
This could be me failing at Perl but just in case...

The `-r` option is enabled by default and in most cases is exactly what's wanted. In my case I wanted to disable the recursive watches but I don't see any way of doing this without modifying the source.

The same thing can probably be achieved using the path modified regex options but something like `-r=no` or similar is more appropriate.

**Comment by avar** [comment]
You can do this with `--no-recursive` in the style of boolean GNU-like options, I pushed a change to document this explicitly.
